# Menu
menu:
  主页: /
  文章: /archives
  相册: /gallery
  类别: /categories
  标签: /tags
  关于: /about
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/blank-logo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/white-logo.svg

# Content
excerpt_link: Read More...
share_text: Share
nav_text:
  page_prev: Prev page
  page_next: Next page
  post_prev: Newer posts
  post_next: Olde posts

# fancybox
fancybox: false

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Local search
search_text: 搜索
show_count: true
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true

# Gitalk
gitalk:
  enable: false # true
  clientID: 2ba57164627d58effb38 # GitHub Application Client ID
  clientSecret: c6428a566b04c4219f3f91e06997f24cd00e7b8c # Client Secret
  repo: Tomatoro.github.io # Repository name
  owner: Tomatoro # GitHub ID
  admin: Tomatoro # GitHub ID

# Valine
valine:
  enable: true
  el: 'vcomments'
  appId: 'CQjPHxXIXJ8mFQSCGnYpt0vt-gzGzoHsz'
  appKey: 'MKI3gklnGb5sVCOEUmibUD6g'
  notify: true # 邮箱推送
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'

permalink: archives/:abbrlink.html
permalink_defaults:
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hexƒ